version: '3'

services:
  fetchapi:
   image: fetchapi
   ports:
     - 8081
   environment:
     - SERVICE_PORTS=8081
   deploy:
     replicas: 2
     update_config:
       parallelism: 1
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - fetchapi
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
            - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay
